import { Inter } from 'next/font/google'
import './globals.css'

import RootLayouts from './features/core/layouts/RootLayouts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayouts children={children} />
      </body>
    </html>
  )
}
